name: Build and deploy website

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'api/**'
      - 'web2/**'
      - 'docs/**'
      - 'images/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'api/**'
      - 'web2/**'
      - 'docs/**'
      - 'images/**'

jobs:
  build_website:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build website
      run: npm run build
    
    - name: Run unit tests
      run: npm run test

    - name: Upload build files
      uses: actions/upload-artifact@v3
      with:
        path: ./web/build
  
  deploy_website:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: build_website
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-website.yml
        workflow_conclusion: success

    - name: Deploy artifacts to a repo
      uses: tagus/git-deploy@v0.4.1
      with:
        changes: artifact
        repository: git@github.com:clydedz/webdeploy-monorepo-poc.git
        ssh_key: ${{ secrets.REPO_DEPLOY_KEY }}
        name: clydedz
        email: 13506613+ClydeDz@users.noreply.github.com
        clean_repo: true
        branch: main
        message: "Commit from the monorepo website deploy action"