name: Deploy images

on:
  workflow_run:
    workflows: ["Build images"]
    branches: [main]
    types: [completed]

jobs:
  deploy_images:
    name: Deploy images
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-images.yml
        workflow_conclusion: success

    - name: Deploy artifacts to a repo
      uses: tagus/git-deploy@v0.4.1
      with:
        changes: artifact
        repository: git@github.com:clydedz/webdeploy-monorepo-poc.git
        ssh_key: ${{ secrets.REPO_DEPLOY_KEY }}
        name: clydedz
        email: 13506613+ClydeDz@users.noreply.github.com
        clean_repo: true
        branch: gh-pages
        message: "Commit from the monorepo images deploy action"
